%YAML:1.0

#common parameters
imu_topic: "/rtimulib_node/imu"
image_topic: "/camera/image_raw"
output_path: "/home/midsky/MiSVINS/output/"
extractor_onnx_path: "weights/480_640_1024_extractor_sim.onnx"
matcher_onnx_path: "weights/480_640_1024_matcher_sim.onnx"
extractor_engine_path: "trt_weights/extractor_480x640_1024.engine"
matcher_engine_path: "trt_weights/matcher_dynamic_num_keypoints_1024.engine"

#camera calibration 
model_type: PINHOLE
camera_name: camera
image_width:  968 # 640
image_height: 608    # 512
distortion_parameters:
   k1: -0.1255945656257394  # -0.06125568297136998
   k2: 0.053221287232781606  # -0.003796743395135256
   p1: 9.94070021080493e-05  # 0.027326634771204592
   p2: 9.550660927242349e-05  # -0.030296403142887066
projection_parameters:
   fx: 543.3327734182214  # 413.32595366566017
   fy: 542.398772982566  # 413.70198739483686
   cx: 489.02536042247897  # 305.9507483284928
   cy: 305.38727712002805  # 259.4439948946375

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 0   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.
                        # 2  Don't know anything about extrinsic parameters. You don't need to give R,T. We will try to calibrate it. Do some rotation movement at beginning.                        
#If you choose 0 or 1, you should write down the following matrix.
#Rotation from camera frame to imu frame, imu^R_cam
extrinsicRotation: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [-0.99937221, -0.03437489, -0.00857581,
           0.00901561, -0.01265975, -0.99987922, 
           0.03426217, -0.99932882, 0.01296171]
#Translation from camera frame to imu frame, imu^T_cam
extrinsicTranslation: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [-0.01928963, -0.17514254, -0.0267952]

#feature traker paprameters
max_cnt: 256            # max feature number in feature tracking
min_dist: 30        # min distance between two features 
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
equalize: 1             # if image is too dark or light, trun on equalize to find enough features
fisheye: 0              # if using fisheye, trun on it. A circle mask will be loaded to remove edge noisy points

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel) 10.0

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 0.05          # accelerometer measurement noise standard deviation. #0.2   0.04  0.02
gyr_n: 0.003         # gyroscope measurement noise standard deviation.     #0.05  0.004  0.001
acc_w: 0.0015         # accelerometer bias random work noise standard deviation.  #0.02  0.001  0.00005
gyr_w: 0.0001      # gyroscope bias random work noise standard deviation.     #4.0e-5
g_norm: 9.81007     # gravity magnitude

#loop closure parameters
loop_closure: 0                    # start loop closure
load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
fast_relocalization: 0             # useful in real-time and large project
pose_graph_save_path: "/home/midsky/MiSVINS/output/pose_graph/" # save and load path

#unsynchronization parameters
estimate_td: 0                      # online estimate time offset between camera and imu
td: -0.053694112369382575                             # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock) -0.0403806549886

#rolling shutter parameters
rolling_shutter: 0                  # 0: global shutter camera, 1: rolling shutter camera
rolling_shutter_tr: 0               # unit: s. rolling shutter read out time per frame (from data sheet). 

#visualization parameters
save_image: 1                   # save image in pose graph for visualization prupose; you can close this function by setting 0 
visualize_imu_forward: 0        # output imu forward propogation to achieve low latency and high frequence results
visualize_camera_size: 0.4      # size of camera marker in RVIZ
